apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  labels:
    app: websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket-server
        image: rmsdud2435/websocket-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: WEBSOCKET_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: websocket-config
              key: WEBSOCKET_SERVER_PORT
        - name: WEBSOCKET_SERVER_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: websocket-config
              key: WEBSOCKET_SERVER_CONTEXT_PATH
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: websocket-config
              key: KAFKA_BROKER
        - name: KAFKA_BROKER_PORT
          valueFrom:
            configMapKeyRef:
              name: websocket-config
              key: KAFKA_BROKER_PORT
        - name: CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: websocket-config
              key: CONSUMER_GROUP
