apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  labels:
    app: websocket-server
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: websocket-server
